baseurl = "https://www.knowsuchagency.com"
title = "knowsuchagency"

googleAnalytics = "UA-169338852-1"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyURLs = true

pygmentsstyle = "friendly"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "knowsuchagency corp"
    description = "knowsuchagency"
    keywords = "blog,python,consulting,training,business,cloud"
    info = "engineering excellence"
    avatarurl = "images/logo.png"
    footercontent = "Stephan Fitzpatrick"

    favicon_32 = "images/logoFull.png"
    # favicon_16 = "favicon.png"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"
    hideColorSchemeToggle = true


    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    customCSS = ["css/color.css"]
    # customSCSS = ["scss/fonts.scss"]

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/knowsuchagency/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/fitzpatrickstephan/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 1
    url = "https://twitter.com/knowsuchagency/"

[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook"
    weight = 2
    url = "https://www.facebook.com/knowsuchagency"

[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 2
    url = "https://www.instagram.com/knowsuchagency/"


[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://knowsuchagency.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 4
            url = "contact/"

            [[languages.en.menu.main]]
            name = "Book"
            weight = 5
            url = "book/"

[notebooks]

    [notebooks.a-moment-of-monoids]
    draft = false
    date = 2019-12-28
    title = "A Moment of Monoids"
    description = "You already know monoids"
    slug = "a-moment-of-monoids"
    tags = ["python", "functional-programming", "math"]
    series = ["functional programming"]

    [notebooks.monads-in-python]
    draft = false
    date = 2020-01-17
    title = "Monads for Mortals (in Python)"
    description = "Implementing the Identity Monad in Python"
    slug = "monads-for-mortals-in-python"
    tags = ["python", "functional programming", "math", "testing"]
    series = ["functional programming"]

    [notebooks.collatz-conjecture]
    draft = false
    date = 2017-10-30
    title = "Collatz Conjecture"
    description = "Collatz Conjecture in Python"
    slug = "collatz-conjecture-in-python"
    tags = ["python", "math", "programming"]

    [notebooks.postmodern-error-handling]
    draft = false
    date = 2017-02-24
    title = "Postmodern Error Handling in Python 3"
    description = "An exploration of error handling in Python"
    slug = "postmodern-error-handling"
    tags = ["python", "error-handling", "programming"]

    [notebooks.illegal-states]
    draft = false
    date = 2017-09-20
    title = "Domain Modeling for Great Good"
    description = "Making illegal states unrepresentable"
    slug = "avoiding-illegal-state-through-domain-modeling"
    tags = ["python", "architecture", "domain modeling", "programming"]

    [notebooks.mbp-sentiment-analysis]
    draft = false
    date = 2016-10-28
    title = "Sentiment Analysis of the new Macbook Pro"
    description = "What does reddit think of the new macbook pro"
    slug = "mbp-sentiment-analysis"
    tags = ["python", "sentiment analysis", "reddit", "programming"]
