name: github pages

on:
  push:
    branches:
    - src

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: pdm-project/setup-pdm@v2.1
        name: Setup PDM
        with:
          python-version: 3.8

      - name: Initialize Theme
        run: pdm run init-theme

      - name: Install Dependencies
        run: pdm install

      - name: Render Notebooks
        run: pdm run render-notebooks

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Blog
        run: hugo

      - name: Deploy Blog
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
