name: test

on: pull_request  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: pdm-project/setup-pdm@v1.1
        name: Setup PDM
        with:
          python-version: 3.8
      
      - name: Install Dependencies
        run: pdm install

      - name: Render Notebooks
        run: pdm run render-notebooks

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Blog
        run: hugo
